import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
  parent: {
    flex: 1,
    backgroundColor: "#3f51b5",
  },
  containerHeader: {
    paddingVertical: 20,
    justifyContent: "center",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 0,
  },
  containerSubHeader: {
    flexDirection: "row",
  },
  labelCurrentDay: {
    color: "#FFFFFF",
    fontWeight: "500",
    fontSize: 18,
    alignSelf: "center",
    marginBottom: 40,
  },
  statusDay: {
    flexDirection: "column",
  },
  labelToday: {
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 22,
    marginLeft: 30,
  },
  labelAmountTask: {
    color: "#FFFFFF",
    fontWeight: "normal",
    fontSize: 13,
    marginLeft: 30,
    marginTop: 10,
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 9,
    elevation: 5,
  },
  button: {
    borderRadius: 15,
    padding: 10,
    elevation: 2,
    margin: 10,
  },
  labelButtonAddNew: {
    fontWeight: "bold",
    fontSize: 15,
    color: "#3f51b5",
  },
  touchableAddNewButton: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 20,
    paddingHorizontal: 30,
    borderRadius: 15,
    marginRight: 30,
    marginLeft: "auto",
  },
  buttonClose: {
    backgroundColor: "#FFFFFF",
  },
  buttonAddTask: {
    backgroundColor: "#303f9f",
  },
  labelButtonComplete: {
    backgroundColor: "#5c6bc0",
    padding: 10,
    borderRadius: 10,
    color: "#FFFFFF",
    marginRight: 10,
  },
  touchableButtonDelete: {
    backgroundColor: "#FFFFFF",
    marginRight: 5,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 9,
    elevation: 5,
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  labelGoBack: {
    color: "#d50000",
    fontWeight: "bold",
    textAlign: "center",
  },
  labelButtonAddTask: {
    color: "#3f51b5",
    backgroundColor: "#FFFFFF",
    paddingVertical: 20,
    paddingHorizontal: 30,
    fontWeight: "bold",
    borderRadius: 15,
    marginRight: 30,
    marginLeft: "auto",
    fontSize: 15,
  },
  listTask: {
    backgroundColor: "#FFFFFF",
    flex: 1,
    borderTopStartRadius: 50,
    borderTopEndRadius: 50,
    paddingTop: 30,
  },
  container: {
    padding: 35,
    alignItems: "center",
  },
  inputBox: {
    width: 250,
    borderBottomColor: "#303f9f",
    borderBottomWidth: 2,
    paddingLeft: 8,
    marginBottom: 10,
  },
  listItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 20,
    marginVertical: 10,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 9,
    elevation: 5,
  },
  task: {
    flex: 1,
  },
  error: {
    color: "red",
  },
});
